name: Build Spring Boot App (Windows)

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\.m2\repository
          key: windows-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            windows-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Spring Apps
      #   uses: azure/azure-spring-apps-deploy@v2
      #   with:
      #     app-name: mygithubaction   # Replace with your Azure Spring Apps instance name
      #     resource-group: SakshiveRG  # Replace with your resource group name
      #     plan-name: githubspring # Replace with your App Service plan name
      #     deployment-package: target/*.jar

      # - name: Deploy to Azure Spring Apps
      #   uses: azure/spring-apps-deploy@v1
      #   with:
      #     azure-subscription: d2a80d63-63c2-452d-9dcb-115ac8b2211a
      #     service-name: mygithubaction
      #     app-name: mygithubaction
      #     package: target/*.jar
